// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "fiber@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/authenticate": {
            "post": {
                "description": "Authenticates a user based on email and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Authentication parameters",
                        "name": "authParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AuthParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.genericResp"
                        }
                    }
                }
            }
        },
        "/material": {
            "get": {
                "description": "Get a list of materials based on the provided filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Get materials",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Material ID (optional)",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Material name (optional)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Material color (optional)",
                        "name": "color",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Material size (optional)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Material quantity (optional)",
                        "name": "quantity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Material remarks (optional)",
                        "name": "remarks",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Material"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Insert a new material into the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Insert material",
                "parameters": [
                    {
                        "description": "Material details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.InsertMaterialParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Material"
                        }
                    }
                }
            }
        },
        "/material/colors": {
            "get": {
                "description": "Get a list of unique material colors.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Get material colors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/material/sizes": {
            "get": {
                "description": "Get a list of unique material sizes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Get material sizes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/material/{id}": {
            "delete": {
                "description": "Delete a material from the system.",
                "tags": [
                    "Material"
                ],
                "summary": "Delete material",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Material ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing material in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Update material",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Material ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated material details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateMaterialParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/materialOrder": {
            "get": {
                "description": "Retrieves a list of material orders based on query parameters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MaterialOrder"
                ],
                "summary": "Get material orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Material Order ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Seller ID",
                        "name": "sellerId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Material Order status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.MaterialOrder"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Inserts a new material order.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MaterialOrder"
                ],
                "summary": "Insert material order",
                "parameters": [
                    {
                        "description": "Material Order information",
                        "name": "materialOrder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.InsertMaterialOrderParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.MaterialOrder"
                        }
                    }
                }
            }
        },
        "/materialOrder/{id}": {
            "delete": {
                "description": "Deletes a material order by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MaterialOrder"
                ],
                "summary": "Delete material order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Material Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing material order in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MaterialOrder"
                ],
                "summary": "Update material order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Material Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated material order details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateMaterialOrderParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/order": {
            "get": {
                "description": "Retrieves a list of orders based on query parameters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Get orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "customerId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Order"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Inserts a new order.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Insert order",
                "parameters": [
                    {
                        "description": "Order information",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.InsertOrderParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Order"
                        }
                    }
                }
            }
        },
        "/order/{id}": {
            "delete": {
                "description": "Deletes an order by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Delete order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing order in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Update order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated order details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateOrderParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/processingItem": {
            "get": {
                "description": "Retrieves a list of processing items based on query parameters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processing Item"
                ],
                "summary": "Get processing items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Processing item ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Processing item name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Quantity",
                        "name": "quantity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Price",
                        "name": "price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Worker ID",
                        "name": "workerId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (format: YYYY-MM-DD)",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (format: YYYY-MM-DD)",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "sku",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Remarks",
                        "name": "remarks",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.ProcessingItem"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Inserts a new processing item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processing Item"
                ],
                "summary": "Insert processing item",
                "parameters": [
                    {
                        "description": "Processing item information",
                        "name": "processingItem",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.InsertProcessingItemParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ProcessingItem"
                        }
                    }
                }
            }
        },
        "/processingItem/{id}": {
            "delete": {
                "description": "Deletes a processing item by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processing Item"
                ],
                "summary": "Delete processing item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Processing item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing processing item in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processing Item"
                ],
                "summary": "Update processing item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Processing Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated processing item details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateProcessingItemParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/product": {
            "get": {
                "description": "Retrieves a list of products based on query parameters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Product SKU",
                        "name": "sku",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Product name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Material",
                        "name": "material",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Color",
                        "name": "color",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Quantity",
                        "name": "quantity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Price",
                        "name": "price",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date (format: YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Remark",
                        "name": "remark",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Product"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Inserts a new product.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Insert product",
                "parameters": [
                    {
                        "description": "Product information",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.InsertProductParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Product"
                        }
                    }
                }
            }
        },
        "/product/{id}": {
            "delete": {
                "description": "Deletes a product by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Delete product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing product in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Update product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated product details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateProductParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/worker": {
            "get": {
                "description": "Retrieves a list of workers based on query parameters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Get workers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Company name",
                        "name": "company",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Worker name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Phone number",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Address",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tax ID number",
                        "name": "taxIdNumber",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Worker"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Inserts a new worker.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Insert worker",
                "parameters": [
                    {
                        "description": "Worker information",
                        "name": "worker",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.InsertWorkerParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Worker"
                        }
                    }
                }
            }
        },
        "/worker/{id}": {
            "delete": {
                "description": "Deletes a worker by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Delete worker",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing worker in the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Worker"
                ],
                "summary": "Update worker",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated worker details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateWorkerParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AuthParams": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/types.User"
                }
            }
        },
        "api.InsertMaterialOrderItemParams": {
            "type": "object",
            "properties": {
                "material": {
                    "$ref": "#/definitions/api.InsertMaterialOrderMaterialParams"
                },
                "quantity": {
                    "type": "integer"
                },
                "totalPrice": {
                    "type": "number"
                }
            }
        },
        "api.InsertMaterialOrderMaterialParams": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "api.InsertMaterialOrderParams": {
            "type": "object",
            "properties": {
                "deliveryDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "materialOrderItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.InsertMaterialOrderItemParams"
                    }
                },
                "orderDate": {
                    "type": "string"
                },
                "paymentDate": {
                    "type": "string"
                },
                "sellerID": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "api.InsertMaterialParams": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "api.InsertOrderItemParams": {
            "type": "object",
            "properties": {
                "product": {
                    "$ref": "#/definitions/api.InsertOrderProductParams"
                },
                "quantity": {
                    "type": "integer"
                },
                "totalPrice": {
                    "type": "number"
                }
            }
        },
        "api.InsertOrderParams": {
            "type": "object",
            "properties": {
                "customerId": {
                    "type": "string"
                },
                "deliveryDate": {
                    "type": "string"
                },
                "orderDate": {
                    "type": "string"
                },
                "orderItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.InsertOrderItemParams"
                    }
                },
                "paymentDate": {
                    "type": "string"
                },
                "shippingAddress": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "api.InsertOrderProductParams": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                },
                "unitPrice": {
                    "type": "number"
                }
            }
        },
        "api.InsertProcessingItemParams": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "workerId": {
                    "type": "string"
                }
            }
        },
        "api.InsertProductParams": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "material": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "api.InsertWorkerParams": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "taxIdNumber": {
                    "type": "string"
                }
            }
        },
        "api.UpdateMaterialOrderParams": {
            "type": "object",
            "properties": {
                "deliveryDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderDate": {
                    "type": "string"
                },
                "paymentDate": {
                    "type": "string"
                },
                "sellerID": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "api.UpdateMaterialParams": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "api.UpdateOrderItemParams": {
            "type": "object",
            "properties": {
                "product": {
                    "$ref": "#/definitions/api.UpdateOrderProductParams"
                },
                "quantity": {
                    "type": "integer"
                },
                "totalPrice": {
                    "type": "number"
                }
            }
        },
        "api.UpdateOrderParams": {
            "type": "object",
            "properties": {
                "customerId": {
                    "type": "string"
                },
                "deliveryDate": {
                    "type": "string"
                },
                "orderDate": {
                    "type": "string"
                },
                "orderItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.UpdateOrderItemParams"
                    }
                },
                "paymentDate": {
                    "type": "string"
                },
                "shippingAddress": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "api.UpdateOrderProductParams": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                },
                "unitPrice": {
                    "type": "number"
                }
            }
        },
        "api.UpdateProcessingItemParams": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "workerId": {
                    "type": "string"
                }
            }
        },
        "api.UpdateProductParams": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "material": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "api.UpdateWorkerParams": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "taxIdNumber": {
                    "type": "string"
                }
            }
        },
        "api.genericResp": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "fiber.Map": {
            "type": "object",
            "additionalProperties": true
        },
        "types.Material": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.PriceHistoryEntry"
                    }
                },
                "quantity": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "types.MaterialOrder": {
            "type": "object",
            "properties": {
                "deliveryDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "materialOrderItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.MaterialOrderItem"
                    }
                },
                "orderDate": {
                    "type": "string"
                },
                "paymentDate": {
                    "type": "string"
                },
                "sellerId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "types.MaterialOrderItem": {
            "type": "object",
            "properties": {
                "material": {
                    "$ref": "#/definitions/types.MaterialOrderMaterial"
                },
                "quantity": {
                    "type": "integer"
                },
                "totalPrice": {
                    "type": "number"
                }
            }
        },
        "types.MaterialOrderMaterial": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "remarks": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "types.Order": {
            "type": "object",
            "properties": {
                "customerId": {
                    "type": "string"
                },
                "deliveryDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderDate": {
                    "type": "string"
                },
                "orderItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.OrderItem"
                    }
                },
                "paymentDate": {
                    "type": "string"
                },
                "shippingAddress": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "types.OrderItem": {
            "type": "object",
            "properties": {
                "product": {
                    "$ref": "#/definitions/types.OrderProduct"
                },
                "quantity": {
                    "type": "integer"
                },
                "totalPrice": {
                    "type": "number"
                }
            }
        },
        "types.OrderProduct": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                },
                "unitPrice": {
                    "type": "number"
                }
            }
        },
        "types.PriceHistoryEntry": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "types.ProcessingItem": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "workerId": {
                    "type": "string"
                }
            }
        },
        "types.Product": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "material": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "types.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                }
            }
        },
        "types.Worker": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "taxIdNumber": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Fiber Example API",
	Description:      "This is a sample swagger for Fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
